pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'jdk21'
    }

    environment {
        EXCEL_PATH = "/data/excel/testdata.xlsx"
        FILE_PATH  = "/data/files/ABC.txt"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/asrafulmd12/Wipro-traning.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'mvn clean test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'mvn package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'docker build -t automation-testing-practice .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                bat '''
                docker run --rm ^
                -e EXCEL_PATH=/data/excel/testdata.xlsx ^
                -e FILE_PATH=/data/files/ABC.txt ^
                -v D:\\ExcelTest:/data/excel ^
                -v E:\\Text:/data/files ^
                automation-testing-practice
                '''
            }
        }
    }

    post {

        always {


            archiveArtifacts artifacts: 'Automation_Testing_Practice/test-output/**/*.*',
                             allowEmptyArchive: true

            archiveArtifacts artifacts: 'Automation_Testing_Practice/target/**/*.*',
                             allowEmptyArchive: true,
                             fingerprint: true
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}