pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'jdk21'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/asrafulmd12/Wipro-traning.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'mvn clean test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'mvn package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'docker build -t automation_testing_practice .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'docker run --rm automation_testing_practice'
                }
            }
        }
    }

    post {

        always {

            archiveArtifacts artifacts: 'Automation_Testing_Practice/target/**/*.*',
                             allowEmptyArchive: true,
                             fingerprint: true

            archiveArtifacts artifacts: 'Automation_Testing_Practice/test-output/**/*.*',
                             allowEmptyArchive: true
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}