pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'jdk'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/asrafulmd12/Wipro-traning.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('Testing') {
                    bat 'mvn clean test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Testing') {
                    bat 'docker build -t testing .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                dir('Testing') {
                    bat 'docker run --rm testing'
                }
            }
        }
    }

    post {
        always {
            junit allowEmptyResults: true,
                  testResults: 'Testing/target/surefire-reports/*.xml'

            archiveArtifacts artifacts: 'Testing/target/**/*.*',
                             fingerprint: true
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}